<h2>Modeling situation</h2>
<p>Your program will have access to the <code class="language-python">exception_test()</code> function, which can throw exceptions.</p>
<p>You need to write code that runs this function, then catches <code class="language-python">ArithmeticError</code>, <code class="language-python">AssertionError</code>, <code class="language-python">ZeroDivisionError</code> exceptions and prints the name of the caught exception. Mind the hierarchy of exceptions.</p>
<p>An example solution that you should send for review:</p>
<pre><code class="language-python">try:
    exception_test()
except Exception:
    print("Exception")
except BaseException:
    print("BaseException")</code></pre>
<p><b>Tip:</b> Don't forget about the hierarchy of exceptions. The key to this task is to choose the correct order of except clauses.</p><br><br><font color="gray">Memory limit: 256 MB</font><br><font color="gray">Time limit: 2 seconds</font><br><br>
<b>Caution</b><br><br>
You may see errors in your code or execution results due to missing context. Donâ€™t worry about it, just write the solution and press Check.
<br><br>
